server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/db_dev_dojo
      username: root
      password: 123456
  jpa:
    hibernate:
      ddl-auto: update